# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

pod 'Firebase/Core'

target 'vroom' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for vroom

  target 'vroom-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'vroomTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'vroom-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

end
